# Generated by Django 6.0.4 on 2026-04-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
